### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by Colgaton** [yubu/zabbix-cassandra-template#1]
Hi, when importing this template in Zabbix 2.2 I get the following error:

Incorrect trigger expression. Check expression part starting from " or {Template Custom Cassandra Cluster:jmx["org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=commitlog_archiver,name=CurrentlyBlockedTasks","Count"].last()}>0".

Please advise.

**Comment by peske** [comment]
Chances are that you haven't replaced "Custom" in the file in a consistent way. It is understandable since yubu hasn't spent too much time in documentation obviously :)

So I believe that in your case the problem is in bold part:

Incorrect trigger expression. Check expression part starting from " or {**Template Custom Cassandra Cluster**:jmx["org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=commitlog_archiver,name=CurrentlyBlockedTasks","Count"].last()}>0".

This must be equal to your template name. At the [beginning of the file](https://github.com/yubu/zabbix-cassandra-template/blob/master/zabbix-templates-cassandra-export.xml#L12) you have something like:

```
<template>Template Custom Cassandra Cluster</template>
<name>Template Custom Cassandra Cluster</name>
```

Note that if you change template name "Template Custom Cassandra Cluster", you should change it consistently throughout the file, including the trigger declaration. 

I'm not sure why yubu has made it confusing with these "Custom" replacements, but... In my opinion you should simply replace phrase "Template Custom Cassandra Cluster" with "Template Cassandra Cluster" **throughout the file**. (By convention template names should start with "Template ...")

Also change group names that are appearing only once, at the beginning of the file. As far as I know templates **by convention** should belong to group "Templates" so there were no reason for "Custom" in the first place. So in lines 6 and 16 (or nearby) you'll find something like:

```
<group>
    <name>Custom</name>
</group>
```

change it to:

```
<group>
    <name>Templates</name>
</group>
```

Reload template after that, and everything should work. (It works in my case.)

**Comment by Colgaton** [comment]
Hi peske thank you for the answer, I replaced everything like you said, but now I get:

Incorrect trigger expression. Check expression part starting from " or {Template Cassandra Cluster:jmx["org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=commitlog_archiver,name=CurrentlyBlockedTasks","Count"].last()}>0".

Any idea?

**Comment by yubu** [comment]
Colgaton,
Delete problematic items from .xml. You can add them later if all is OK.
yubu
